name: AWS Role Assumption

on:
  push:
    paths:
      - 'values.yaml' # Adjust the file path as needed

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::694702677705:role/gitactions # Replace YOUR_ACCOUNT_ID
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          audience: sts.amazonaws.com
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          aws-region: us-west-2

      - name: Run AWS CLI Command
        run: |
          aws sts get-caller-identity
          # Add more AWS CLI commands as needed

