name: Helm Upgrade

on:
  push:
    paths:
      - 'values.yaml'

jobs:
  helm_upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: configureawscredentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::694702677705:role/gitactions
        role-session-name: samplerolesession
        aws-region: us-west-2

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm version

    - name: Update EKS Cluster
      run: |
        aws eks update-kubeconfig --name dev-infra-k8s-ops --region us-west-2

    - name: Helm Upgrade
      run: |
        helm upgrade prometheus prometheus/ -f  values.yaml

